In [334]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [335]:
df = pd.read_csv('diabetes.csv')

In [336]:
df.head()

Glucose  Insulin   BMI  Age  Outcome
0      148        0  33.6   50        1
1       85        0  26.6   31        0
2      183        0  23.3   32        1
3       89       94  28.1   21        0
4      137      168  43.1   33        1

In [337]:
df.isna().sum()

Glucose    0
Insulin    0
BMI        0
Age        0
Outcome    0
dtype: int64

In [338]:
df.dtypes


Glucose      int64
Insulin      int64
BMI        float64
Age          int64
Outcome      int64
dtype: object

In [339]:

#Add Graphs to the codebase


In [340]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

X = df.drop(columns=['Outcome'])
y = df['Outcome']

In [341]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

In [342]:
X

array([[ 0.84832379, -0.69289057,  0.20401277,  1.4259954 ],
       [-1.12339636, -0.69289057, -0.68442195, -0.19067191],
       [ 1.94372388, -0.69289057, -1.10325546, -0.10558415],
       ...,
       [ 0.00330087,  0.27959377, -0.73518964, -0.27575966],
       [ 0.1597866 , -0.69289057, -0.24020459,  1.17073215],
       [-0.8730192 , -0.69289057, -0.20212881, -0.87137393]])

In [343]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [344]:
model = GaussianNB()
model.fit(X_train,y_train)


GaussianNB()

In [345]:
# temp = X_test[0]
# print(temp.shape)
# print(temp)
# wau = model.predict(X_test)

In [346]:
y_pred = model.predict(X_test)

In [347]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)


In [348]:
print(f'The accuracy of the model is {accuracy:.2f}')
print(f'The precision of the model is {precision:.2f}')
print(f'The recall score of the model is {recall:.2f}')
print(f'The f1-score of the model is {f1:.2f}')

The accuracy of the model is 0.75
The precision of the model is 0.65
The recall score of the model is 0.64
The f1-score of the model is 0.64


In [349]:
import pickle

In [350]:
filename = 'StandardScaler.sav'
pickle.dump(scaler, open(filename, 'wb'))

In [351]:
filename = 'GaussianNB_model.sav'
pickle.dump(model, open(filename, 'wb'))


In [352]:
print(X_test)

[[-7.16533472e-01  9.56859653e-01  2.54780469e-01  8.30381132e-01]
 [-2.78373437e-01 -6.92890572e-01  4.70543187e-01 -1.04154944e+00]
 [-4.03562018e-01 -6.92890572e-01 -1.51361116e-01 -1.04154944e+00]
 [-4.34859164e-01 -6.92890572e-01 -9.38260437e-01  6.45913543e-02]
 [ 4.72758051e-01 -6.92890572e-01 -2.65588436e-01  1.42599540e+00]
 [-5.60047745e-01  9.56859653e-01  7.24381677e-01  1.85143417e+00]
 [-1.56155640e+00 -3.29904822e-02 -1.47132127e+00 -9.56461683e-01]
 [-1.21887711e-01 -6.92890572e-01  2.29396620e-01  9.15468886e-01]
 [ 1.03610667e+00  4.01154314e-01 -8.79014930e-02  3.19854614e-01]
 [ 8.17026649e-01 -6.92890572e-01  2.16704696e-01  2.70231170e+00]
 [-3.09670582e-01 -6.92890572e-01 -5.70194625e-01  5.75117873e-01]
 [ 1.81853530e+00 -6.92890572e-01  2.80164319e-01  2.27687294e+00]
 [ 8.48323795e-01  2.06827033e+00 -1.38669191e-01 -3.60847411e-01]
 [-7.79127762e-01 -1.11136545e-01  2.04012771e-01  8.30381132e-01]
 [-1.02950492e+00 -5.53964238e-01 -4.55967305e-01 -9.56461683e

In [353]:
print(y_pred)

[0 0 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 1 0 0 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 1 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0
 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0
 0 1 0 0 1 0]
